# Use an optimized image for FastAPI
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.12

# Set the working directory
WORKDIR /app

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    ln -s /opt/poetry/bin/poetry /usr/local/bin/poetry && \
    poetry config virtualenvs.create false

# Copy pyproject.toml and poetry.lock to install dependencies
COPY ./pyproject.toml ./poetry.lock* /app/

# Install dependencies (only main)
RUN poetry install --no-root --only main

# Set the environment variable for the application
ENV PYTHONPATH=/app

# Copy the remaining project files
COPY ./app /app/app

# Default command to run the application
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
